language: cpp

# For Ubuntu 14.04 C++11/15 support ...
sudo: required
dist: trusty

compiler:  
    - gcc

before_script:
    - sudo apt-get install build-essential
    - sudo apt-get install cmake
    - sudo apt-get install libboost-all-dev
    - sudo apt-get install libopencv-dev
    - mkdir build
    - cd build
    - cmake ..

script: make 
